# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: foo_msg/foo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from default_msg import default_pb2 as default__msg_dot_default__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x66oo_msg/foo.proto\x1a\x19\x64\x65\x66\x61ult_msg/default.proto\"\xb3\x02\n\nFooRequest\x12\x18\n\x10\x66oo_string_field\x18\x01 \x01(\t\x12!\n\x19\x66oo_repeated_string_field\x18\x02 \x03(\t\x12\x17\n\x0f\x66oo_int32_field\x18\x03 \x01(\x05\x12 \n\x18\x66oo_repeated_int32_field\x18\x04 \x03(\x05\x12\x17\n\x0f\x66oo_int64_field\x18\x05 \x01(\x03\x12 \n\x18\x66oo_repeated_int64_field\x18\x06 \x03(\x03\x12\x17\n\x0f\x66oo_float_field\x18\x07 \x01(\x02\x12 \n\x18\x66oo_repeated_float_field\x18\x08 \x03(\x02\x12\x16\n\x0e\x66oo_bool_field\x18\t \x01(\x08\x12\x1f\n\x17\x66oo_repeated_bool_field\x18\n \x03(\x08\"#\n\x0b\x46ooResponse\x12\x14\n\x0c\x66oo_response\x18\x01 \x01(\t\"$\n\x0b\x46ooFileInfo\x12\x15\n\rfoo_file_name\x18\x01 \x01(\t\"2\n\x07\x46ooFile\x12\x15\n\rfoo_file_name\x18\x01 \x01(\t\x12\x10\n\x08\x66oo_file\x18\x02 \x01(\x0c\"\x1b\n\tFooStatus\x12\x0e\n\x06status\x18\x01 \x01(\t2\xbe\x01\n\nFooService\x12\'\n\nFooMethod1\x12\x0b.FooRequest\x1a\x0c.FooResponse\x12!\n\nFooMethod2\x12\x0b.FooRequest\x1a\x06.Empty\x12\x33\n\x15\x46ooMethodDownloadFile\x12\x0c.FooFileInfo\x1a\x08.FooFile\"\x00\x30\x01\x12/\n\x13\x46ooMethodUploadFile\x12\x08.FooFile\x1a\n.FooStatus\"\x00(\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'foo_msg.foo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FOOREQUEST._serialized_start=49
  _FOOREQUEST._serialized_end=356
  _FOORESPONSE._serialized_start=358
  _FOORESPONSE._serialized_end=393
  _FOOFILEINFO._serialized_start=395
  _FOOFILEINFO._serialized_end=431
  _FOOFILE._serialized_start=433
  _FOOFILE._serialized_end=483
  _FOOSTATUS._serialized_start=485
  _FOOSTATUS._serialized_end=512
  _FOOSERVICE._serialized_start=515
  _FOOSERVICE._serialized_end=705
# @@protoc_insertion_point(module_scope)
